# Generated by Django 3.0.5 on 2020-06-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='favorited_by',
            field=models.ManyToManyField(related_name='fav', to='recipe.Author'),
        ),
    ]
