# Generated by Django 3.0.5 on 2020-06-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipeitem_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(related_name='fav', to='recipe.RecipeItem'),
        ),
    ]
